function Initialize()
    headsetBatteryMeasure = SKIN:GetMeasure('MeasureBatteryLevel')
end

function Update()
    percent = headsetBatteryMeasure:GetValue();
    
    if percent == 0 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "255"')
    elseif percent > 0 and percent < 10 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 10 and percent < 20 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 20 and percent < 30 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 30 and percent < 40 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 40 and percent < 50 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 50 and percent < 60 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 60 and percent < 70 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 70 and percent < 80 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 80 and percent < 90 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    elseif percent > 90 and percent < 100 then
        SKIN:Bang('!SetOption MeterFullBattery ImageAlpha "255"')
        SKIN:Bang('!SetOption MeterNinetyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEightyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSeventyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterSixtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFiftyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterFourtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterThirtyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTwentyPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterTenPercent ImageAlpha "0"')
        SKIN:Bang('!SetOption MeterEmptyBattery ImageAlpha "0"')
    end


    local textMeter = SKIN:GetMeter('MeterText')
    local textW = textMeter:GetW()

    local battery = SKIN:GetMeter('MeterEmptyBattery')
    local batteryH = battery:GetH()
    local batteryW = battery:GetW()

    local textX = (batteryW / 2) - (textW / 2)
    local textY = batteryH + 10

    SKIN:Bang('!MoveMeter', textX, textY, 'MeterText')
end